backend:
  name: git-gateway
  branch: master
  commit_messages:
    create: "Create {{collection}} “{{slug}}”"
    update: "Update {{collection}} “{{slug}}”"
    delete: "Delete {{collection}} “{{slug}}”"
    uploadMedia: "[skip ci] Upload “{{path}}”"
    deleteMedia: "[skip ci] Delete “{{path}}”"

local_backend: true
media_folder: static/img
public_folder: /img

collections:
  - name: "pages"
    label: "Pages"
    files:
      - file: "src/pages/index.md"
        label: "Landing Page"
        name: "index"
        fields:
          - {
              label: "Template Key",
              name: "templateKey",
              widget: "hidden",
              default: "index-page",
            }
          - { label: 'Link Shopee', name: 'linkShopee', widget: 'string' }
          - { label: 'Link Tokopedia', name: 'linkTokopedia', widget: 'string' }
          - { label: 'Link Instagram', name: 'linkInstagram', widget: 'string' }
          - { label: 'Link Facebook', name: 'linkFacebook', widget: 'string' }
          - { label: 'Link Whatsapp', name: 'linkWhatsapp', widget: 'string' }
          - { label: 'Nomor Whatsapp', name: 'whatsAppNumber', widget: 'string' }
          - { label: 'Email', name: 'email', widget: 'string' }

          - {
            label: Jumbotron,
            name: jumbotron,
            widget: object,
            fields: [
              { label: Judul Utama, name: title, widget: string },
              { label: Deskripsi, name: description, widget: text },
              { label: Gambar, name: image, widget: image },
              { label: Label Belanja, name: shopNowLabel, widget: string },
            ],
          }

          - {
              label: Fitur,
              name: features,
              widget: object,
              fields:
                [
                  { label: Judul, name: heading, widget: string },
                  {
                    label: Daftar Fitur,
                    name: items,
                    widget: list,
                    fields:
                      [
                        { label: Gambar, name: image, widget: image },
                        { label: Nama Produk, name: productName, widget: string },
                        { label: Harga, name: price, widget: string },
                        { label: Link Shopee, name: linkShopee, widget: string },
                        { label: Link Tokopedia, name: linkTokopedia, widget: string },
                      ],
                  }
                ],
            }

          - {
            label: Kelebihan,
            name: strongPoints,
            widget: object,
            fields: [
              { label: Judul, name: heading, widget: string },
              { label: Deskripsi Judul, name: subheading, widget: text },
              {
                label: Daftar Kelebihan,
                name: items,
                widget: list,
                fields:
                  [
                    { label: Gambar, name: image, widget: image },
                    { label: Judul, name: title, widget: string },
                    { label: Deskripsi, name: description, widget: string },
                  ],
              }
            ],
          }

          - {
            label: Testimoni,
            name: testimonies,
            widget: object,
            fields: [
              { label: Judul, name: heading, widget: string },
              { label: Deskripsi Judul, name: subheading, widget: text },
              {
                label: Daftar Testimoni,
                name: items,
                widget: list,
                fields:
                  [
                    { label: Gambar Penulis, name: authorImage, widget: image },
                    { label: Nama Penulis, name: authorName, widget: string },
                    { label: Deskripsi Testimoni, name: description, widget: string },
                  ],
              },
            ],
          }
          
          - {
              label: Support,
              name: support,
              widget: object,
              fields: [
                { label: Judul, name: heading, widget: string },
                { label: Deskripsi Judul, name: subheading, widget: text },
                { label: Label ke Toko, name: goToStoreLabel, widget: text },
                { label: Label Hubungi Kami, name: contactUsLabel, widget: text },
              ],
            }
